apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-app
  labels:
    app: devops-lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-lab-app
  template:
    metadata:
      labels:
        app: devops-lab-app
    spec:
      containers:
      - name: devops-lab-app
        image: 152735632105.dkr.ecr.us-east-1.amazonaws.com/devops-lab-app:latest
        ports:
        - containerPort: 5000

